import type { WordEntry } from "./words";

// This file is generated by scripts/generate-word-data.mjs.
// Do not edit by hand; update scripts/test-words.json or the dictionary source instead.
export const generatedWords = [
  {
    "word": "apple",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "りんご"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "りんご",
          "リンゴの木"
        ]
      }
    ]
  },
  {
    "word": "orange",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "オレンジ"
      },
      {
        "pos": "adjective",
        "definition": "オレンジ色の"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "オレンジ",
          "オレンジ色"
        ]
      },
      {
        "pos": "adjective",
        "definitions": [
          "オレンジ色の"
        ]
      }
    ]
  },
  {
    "word": "water",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "水"
      },
      {
        "pos": "verb",
        "definition": "水をやる"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "水",
          "水域"
        ]
      },
      {
        "pos": "verb",
        "definitions": [
          "水をやる",
          "給水する"
        ]
      }
    ]
  },
  {
    "word": "school",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "学校"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "学校",
          "授業"
        ]
      }
    ]
  },
  {
    "word": "teacher",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "先生"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "先生",
          "教師"
        ]
      }
    ]
  },
  {
    "word": "student",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "生徒"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "生徒",
          "学生"
        ]
      }
    ]
  },
  {
    "word": "family",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "家族"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "家族",
          "家庭"
        ]
      }
    ]
  },
  {
    "word": "morning",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "朝"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "朝",
          "午前"
        ]
      }
    ]
  },
  {
    "word": "garden",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "庭"
      },
      {
        "pos": "verb",
        "definition": "庭仕事をする"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "庭",
          "庭園"
        ]
      },
      {
        "pos": "verb",
        "definitions": [
          "庭仕事をする"
        ]
      }
    ]
  },
  {
    "word": "market",
    "level": 2,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "市場"
      },
      {
        "pos": "verb",
        "definition": "販売する"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "市場",
          "マーケット"
        ]
      },
      {
        "pos": "verb",
        "definitions": [
          "販売する",
          "売り込む"
        ]
      }
    ]
  },
  {
    "word": "station",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "駅"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "駅",
          "署",
          "放送局"
        ]
      }
    ]
  },
  {
    "word": "library",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "図書館"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "図書館",
          "蔵書"
        ]
      }
    ]
  },
  {
    "word": "picture",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "写真"
      },
      {
        "pos": "verb",
        "definition": "想像する"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "写真",
          "絵",
          "画像"
        ]
      },
      {
        "pos": "verb",
        "definitions": [
          "想像する",
          "心に描く"
        ]
      }
    ]
  },
  {
    "word": "question",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "質問"
      },
      {
        "pos": "verb",
        "definition": "質問する"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "質問",
          "問題"
        ]
      },
      {
        "pos": "verb",
        "definitions": [
          "質問する",
          "疑う"
        ]
      }
    ]
  },
  {
    "word": "answer",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "答え"
      },
      {
        "pos": "verb",
        "definition": "答える"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "答え",
          "回答"
        ]
      },
      {
        "pos": "verb",
        "definitions": [
          "答える",
          "返事をする"
        ]
      }
    ]
  },
  {
    "word": "travel",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "旅行"
      },
      {
        "pos": "verb",
        "definition": "旅行する"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "旅行"
        ]
      },
      {
        "pos": "verb",
        "definitions": [
          "旅行する",
          "移動する"
        ]
      }
    ]
  },
  {
    "word": "listen",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "verb",
        "definition": "聞く"
      }
    ],
    "meanings": [
      {
        "pos": "verb",
        "definitions": [
          "聞く",
          "耳を傾ける"
        ]
      }
    ]
  },
  {
    "word": "write",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "verb",
        "definition": "書く"
      }
    ],
    "meanings": [
      {
        "pos": "verb",
        "definitions": [
          "書く",
          "手紙を書く"
        ]
      }
    ]
  },
  {
    "word": "practice",
    "level": 2,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "練習"
      },
      {
        "pos": "verb",
        "definition": "練習する"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "練習",
          "実践"
        ]
      },
      {
        "pos": "verb",
        "definitions": [
          "練習する",
          "実践する"
        ]
      }
    ]
  },
  {
    "word": "remember",
    "level": 2,
    "primaryMeanings": [
      {
        "pos": "verb",
        "definition": "覚えている"
      }
    ],
    "meanings": [
      {
        "pos": "verb",
        "definitions": [
          "覚えている",
          "思い出す"
        ]
      }
    ]
  },
  {
    "word": "beautiful",
    "level": 2,
    "primaryMeanings": [
      {
        "pos": "adjective",
        "definition": "美しい"
      }
    ],
    "meanings": [
      {
        "pos": "adjective",
        "definitions": [
          "美しい",
          "きれいな"
        ]
      }
    ]
  },
  {
    "word": "important",
    "level": 2,
    "primaryMeanings": [
      {
        "pos": "adjective",
        "definition": "重要な"
      }
    ],
    "meanings": [
      {
        "pos": "adjective",
        "definitions": [
          "重要な",
          "大切な"
        ]
      }
    ]
  },
  {
    "word": "different",
    "level": 2,
    "primaryMeanings": [
      {
        "pos": "adjective",
        "definition": "違った"
      }
    ],
    "meanings": [
      {
        "pos": "adjective",
        "definitions": [
          "違った",
          "異なる"
        ]
      }
    ]
  },
  {
    "word": "weather",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "天気"
      },
      {
        "pos": "verb",
        "definition": "切り抜ける"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "天気",
          "天候"
        ]
      },
      {
        "pos": "verb",
        "definitions": [
          "切り抜ける",
          "風雨にさらす"
        ]
      }
    ]
  },
  {
    "word": "season",
    "level": 1,
    "primaryMeanings": [
      {
        "pos": "noun",
        "definition": "季節"
      },
      {
        "pos": "verb",
        "definition": "味付けする"
      }
    ],
    "meanings": [
      {
        "pos": "noun",
        "definitions": [
          "季節",
          "時期"
        ]
      },
      {
        "pos": "verb",
        "definitions": [
          "味付けする"
        ]
      }
    ]
  }
] satisfies WordEntry[];
